version: '1.0.{build}'
image: 
  - Visual Studio 2017
  - Ubuntu
branches:
  only:
  - master
build:
  verbosity: minimal
  configuration: Debug
  publish_nuget: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
artifacts:
  - path: '**\*.nupkg'
    name: nuget
    