version: '1.0.{build}'
image: 
  - Visual Studio 2017
  - Ubuntu
branches:
  only:
  - master
before_build:
  - dotnet restore
build_script:
  - dotnet pack src/VersionDb/VersionDb.csproj --include-symbols -o ./
  - dotnet pack src/VersionDb.Client/VersionDb.Client.csproj --include-symbols -o ./
  - dotnet pack src/VersionDb.Etcd/VersionDb.Etcd.csproj --include-symbols -o ./
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
artifacts:
  - path: '**\*.nupkg'
    name: nuget
    